# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0010_auto_20170607_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='watch_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bg', models.FileField(upload_to='')),
            ],
        ),
    ]
