# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0011_watch_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch_category',
            name='display_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watch_category',
            name='icon',
            field=models.FileField(default='a', upload_to=''),
            preserve_default=False,
        ),
    ]
