# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 14:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0013_watch_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
