# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-14 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0014_auto_20170809_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='pic2',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watch',
            name='pic3',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
