# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0015_auto_20170814_0434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='pic',
            new_name='pic2_l',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='pic2',
            new_name='pic2_s',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='pic3',
            new_name='pic3_l',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='large_pic',
        ),
        migrations.AddField(
            model_name='watch',
            name='pic3_s',
            field=models.ImageField(default=1, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watch',
            name='pic_l',
            field=models.ImageField(default=1, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watch',
            name='pic_s',
            field=models.ImageField(default=1, upload_to=b''),
            preserve_default=False,
        ),
    ]
