# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0016_auto_20170821_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='pic',
            field=models.ImageField(default=1, upload_to=b''),
            preserve_default=False,
        ),
    ]
