# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0017_watch_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='pic4_l',
            field=models.ImageField(default=1, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watch',
            name='pic4_s',
            field=models.ImageField(default=1, upload_to=b''),
            preserve_default=False,
        ),
    ]
