# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-02 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0020_auto_20170902_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='movement',
            field=models.CharField(choices=[(b'automatic', b'\xe8\x87\xaa\xe5\x8b\x95\xe9\x8c\xb6'), (b'manual', b'\xe6\xa9\x9f\xe6\xa2\xb0\xe9\x8c\xb6')], max_length=50, verbose_name=b'Movement'),
        ),
    ]
