# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-08 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0022_auto_20170908_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[(b'commercial', b'\xe9\x8c\xb6\xe8\xa1\x8c'), (b'personal', b'\xe5\x80\x8b\xe4\xba\xba')], max_length=50, verbose_name=b'\xe6\x9c\x83\xe5\x93\xa1\xe9\xa1\x9e\xe5\x9e\x8b')),
            ],
        ),
        migrations.AlterField(
            model_name='watch',
            name='case_size',
            field=models.CharField(blank=True, choices=[(b'<26', b'<26 mm'), (b'26-30', b'26-30 mm'), (b'31-35', b'31-35 mm'), (b'36-39', b'36-39 mm'), (b'40-41', b'40-41 mm'), (b'42-43', b'42-43mm'), (b'>43', b'>43 mm')], max_length=50, verbose_name=b'\xe9\x8c\xb6\xe9\x9d\xa2\xe5\xa4\xa7\xe5\xb0\x8f'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='movement',
            field=models.CharField(choices=[(b'automatic', b'\t\xe8\x87\xaa\xe5\x8b\x95\xe7\x99\xbc\xe6\xa2\x9d'), (b'manual', b'\xe6\xa9\x9f\xe6\xa2\xb0\xe9\x8c\xb6')], max_length=50, verbose_name=b'\xe6\xa9\x9f\xe8\x8a\xaf'),
        ),
    ]
