# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0023_auto_20170908_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='des',
            field=models.CharField(default='hi', max_length=2000, verbose_name=b'\xe8\xa9\xb3\xe7\xb4\xb0\xe4\xbb\x8b\xe7\xb4\xb9'),
            preserve_default=False,
        ),
    ]
