# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 09:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watch', '0026_auto_20170921_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'personal', b'\xe7\xa7\x81\xe4\xba\xba'), (b'commercial', b'\xe9\x8c\xb6\xe8\xa1\x8c')], max_length=20, verbose_name=b'\xe6\xac\xbe\xe5\xbc\x8f')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
