# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0027_auto_20170921_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('personal', '私人'), ('commercial', '錶行')], max_length=20, verbose_name='款式'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='case_material',
            field=models.CharField(max_length=30, null=True, verbose_name='錶面材料'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='case_size',
            field=models.CharField(blank=True, choices=[('<26', '<26 mm'), ('26-30', '26-30 mm'), ('31-35', '31-35 mm'), ('36-39', '36-39 mm'), ('40-41', '40-41 mm'), ('42-43', '42-43mm'), ('>43', '>43 mm')], max_length=50, null=True, verbose_name='錶面大小'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='code',
            field=models.CharField(max_length=20, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='color',
            field=models.CharField(blank=True, choices=[('black', '黑'), ('bronze', '銅'), ('champagne', '香濱金'), ('green', '綠'), ('navy', '海軍藍'), ('silver', '銀'), ('white', '白'), ('beige', '米'), ('blue', '藍'), ('brown', '啡'), ('pink', '粉紅'), ('black', '黑'), ('bronze', '銅'), ('champagne', '香濱金'), ('green', '綠'), ('navy', '海軍藍'), ('silver', '銀'), ('white', '白'), ('beige', '米'), ('blue', '藍'), ('brown', '啡'), ('pink', '粉紅')], max_length=30, null=True, verbose_name='顏色'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='des',
            field=models.CharField(max_length=2000, null=True, verbose_name='詳細介紹'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='movement',
            field=models.CharField(choices=[('automatic', '\t自動發條'), ('manual', '機械錶')], max_length=50, null=True, verbose_name='機芯'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='名稱'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='watch',
            name='pic2_l',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='watch',
            name='pic2_s',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='watch',
            name='pic3_l',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='watch',
            name='pic3_s',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='watch',
            name='pic4_l',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='watch',
            name='pic4_s',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='watch',
            name='pic_l',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='watch',
            name='pic_s',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='watch',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='watch',
            name='ref_no',
            field=models.CharField(max_length=30, null=True, verbose_name='Ref. No.'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='style',
            field=models.CharField(blank=True, choices=[('casual', '休閒'), ('military', '軍事'), ('pilot', '機師'), ('sport', '運動'), ('dive', '潛水'), ('dress', '晚宴'), ('racing', '賽車')], max_length=50, null=True, verbose_name='款式'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='type',
            field=models.CharField(choices=[('all', '男女款'), ('men', '男款'), ('women', '女款')], max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='year',
            field=models.CharField(max_length=10, null=True, verbose_name='Year'),
        ),
    ]
