# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0030_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='featured',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='watch',
            name='pic4_l',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
