# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0031_auto_20171003_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='case_material',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=b'\xe9\x8c\xb6\xe9\x9d\xa2\xe6\x9d\x90\xe6\x96\x99'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Code'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='des',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name=b'\xe8\xa9\xb3\xe7\xb4\xb0\xe4\xbb\x8b\xe7\xb4\xb9'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='movement',
            field=models.CharField(blank=True, choices=[(b'automatic', b'\t\xe8\x87\xaa\xe5\x8b\x95\xe7\x99\xbc\xe6\xa2\x9d'), (b'manual', b'\xe6\xa9\x9f\xe6\xa2\xb0\xe9\x8c\xb6')], max_length=50, null=True, verbose_name=b'\xe6\xa9\x9f\xe8\x8a\xaf'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='name',
            field=models.CharField(max_length=50, verbose_name=b'\xe5\x90\x8d\xe7\xa8\xb1'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='watch',
            name='pic2_l',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='watch',
            name='pic2_s',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='watch',
            name='pic3_l',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='watch',
            name='pic3_s',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='watch',
            name='pic4_s',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='watch',
            name='pic_l',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='watch',
            name='pic_s',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='watch',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watch',
            name='ref_no',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=b'Ref. No.'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='type',
            field=models.CharField(blank=True, choices=[(b'all', b'\xe7\x94\xb7\xe5\xa5\xb3\xe6\xac\xbe'), (b'men', b'\xe7\x94\xb7\xe6\xac\xbe'), (b'women', b'\xe5\xa5\xb3\xe6\xac\xbe')], max_length=50, null=True, verbose_name=b'Type'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'Year'),
        ),
    ]
